executor: CeleryExecutor

dags:
  persistence:
    enabled: true
    storageClassName: microk8s-hostpath
    size: 5Gi
  gitSync:
    enabled: false

# Remove the invalid hostPath config and update to use proper volumes config
extraVolumes:
  - name: airflow-dags
    hostPath:
      path: /home/raghu/data-platform/applications/airflow-dags
      type: Directory

extraVolumeMounts:
  - name: airflow-dags
    mountPath: /opt/airflow/dags
    readOnly: true

logs:
  persistence:
    enabled: true
    storageClassName: microk8s-hostpath
    size: 10Gi

webserver:
  service:
    type: ClusterIP

workers:
  replicas: 2

# Connection to PostgreSQL
data:
  metadataConnection:
    user: db_user
    pass: db_pass
    host: postgres-postgresql.data.svc.cluster.local
    port: 5432
    db: analytics

ingress:
  enabled: true
  hosts:
    - host: airflow.data-platform.local
      paths: ["/"]