image: ghcr.io/dbt-labs/dbt-postgres:1.7.1
command: ["sleep", "infinity"]
env:
  - name: DBT_PROFILES_DIR
    value: /root/.dbt
  - name: DBT_PROJECT_DIR
    value: /dbt
volumeMounts:
  - name: dbt-profiles
    mountPath: /root/.dbt
  - name: dbt-project
    mountPath: /dbt
volumes:
  - name: dbt-profiles
    hostPath:
      path: /home/raghu/data-platform/applications/dbt/profiles
  - name: dbt-project
    hostPath:
      path: /home/raghu/data-platform/applications/dbt/project
