accessKey: minioadmin
secretKey: minioadmin
mode: standalone
persistence:
  storageClass: microk8s-hostpath
  size: 500Gi

service:
  type: ClusterIP

resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "1Gi"
    cpu: "500m"

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  ingressClassName: nginx
  hosts:
    - minio.data-platform.local
  path: "/"
  pathType: "Prefix"
  tls:
    - secretName: minio-tls
      hosts:
        - minio.data-platform.local