auth:
  username: db_user
  password: db_pass
  database: analytics
  postgresPassword: admin_pass

primary:
  persistence:
    enabled: true
    storageClass: microk8s-hostpath
    size: 20Gi
  service:
    type: ClusterIP
    port: 5432

backup:
  enabled: true
  schedule: "0 0 * * *"
  retention: 7
  storage:
    storageClass: ${STORAGE_CLASS:-microk8s-hostpath}
    size: 10Gi

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  ingressClassName: nginx
  hosts:
    - name: postgres.brahma
      path: /
      pathType: Prefix
  tls:
    - secretName: postgres-tls
      hosts:
        - postgres.brahma
