master:
  webPort: 8080
  persistence:
    enabled: true
    storageClass: microk8s-hostpath
    size: 10Gi

worker:
  webPort: 8081
  replicas: 2
  persistence:
    enabled: true
    storageClass: microk8s-hostpath
    size: 20Gi

ingress:
  enabled: true
  hosts:
    - host: spark.data-platform.local
      paths: ["/"]
